services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '3001:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev

volumes:
  postgres-data:
