FROM public.ecr.aws/docker/library/node:24-alpine AS build

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Ideally we'd utilize "pnpm fetch" here and only copy the root package.json (for corepack) and pnpm-lock.yaml, but that
# is not working right now in monorepos: https://github.com/pnpm/pnpm/issues/6058
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml /build/
{%- if features contains "app-config" %}
COPY packages/app-config/package.json /build/packages/app-config/
{%- endif %}
COPY packages/api/package.json /build/packages/api/
WORKDIR /build
RUN pnpm install

COPY . /build
RUN pnpm -r --filter=api{% if features contains "app-config" %} --filter=app-config{% endif %} build
RUN pnpm deploy --filter=api --prod /prod/api

FROM public.ecr.aws/docker/library/node:24-alpine AS api
COPY --from=build /prod/api/dist /api
COPY --from=build /prod/api/package.json /api/
COPY --from=build /prod/api/node_modules /api/node_modules
WORKDIR /api
ENV NODE_ENV="production"
CMD [ "node", "--enable-source-maps", "--import=./register-crash-logger.js", "./index.js" ]
